on:
  push:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Install Host Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.7.2
        host: 'linux'
        target: 'desktop'
        arch: 'linux_gcc_64'
        modules: 'qtshadertools'
        tools: 'tools_ninja tools_cmake'
        dir: '${{ runner.temp }}'
        install-deps: 'true'
        cache: true

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.7.2
        host: 'linux'
        target: 'android'
        arch: 'android_arm64_v8a'
        modules: 'qtshadertools'
        dir: '${{ runner.temp }}'
        install-deps: 'true'
        cache: true

    - name: Build ecm
      run: |
        git clone https://invent.kde.org/frameworks/extra-cmake-modules ${{ runner.temp }}/ecm
        cd ${{ runner.temp }}/ecm
        git checkout v6.5.0
        cmake .
        cmake --build .
        cmake --install . --prefix ${{ env.QT_ROOT_DIR }}/

    - name: Configure
      run: ${{ env.QT_ROOT_DIR }}/bin/qt-cmake -B build
                            -DQT_HOST_PATH=${{ env.QT_ROOT_DIR }}/../gcc_64/
                            -DQt6LinguistTools_DIR=${{ env.QT_ROOT_DIR }}/../gcc_64/lib/cmake/Qt6LinguistTools
                            -DQt6ShaderToolsTools_DIR=${{ env.QT_ROOT_DIR }}/../gcc_64/lib/cmake/Qt6ShaderToolsTools || cmake -B build

    - name: Build
      run: cmake --build .
      working-directory: build

    - name: Save APK
      uses: actions/upload-artifact@v4
      with:
        name: qmlcreator-apk
        path: build/src/android-build/*.apk
